// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPW8cBV1yZd2e6MG-aHKHhflRuHvEKfnI',
    appId: '1:720110906425:web:49215e548b12cf27fff1e8',
    messagingSenderId: '720110906425',
    projectId: 'linerai',
    authDomain: 'linerai.firebaseapp.com',
    storageBucket: 'linerai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfdSWdC0HW58angcBDGobIMTxXG2VVEO8',
    appId: '1:720110906425:android:a42a539275cb2d16fff1e8',
    messagingSenderId: '720110906425',
    projectId: 'linerai',
    storageBucket: 'linerai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_0hP6P0QbK-94cASnG9ktQxMfqVjJsMQ',
    appId: '1:720110906425:ios:aec9b3761e466077fff1e8',
    messagingSenderId: '720110906425',
    projectId: 'linerai',
    storageBucket: 'linerai.firebasestorage.app',
    iosBundleId: 'shop.drippingmonks.linerai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_0hP6P0QbK-94cASnG9ktQxMfqVjJsMQ',
    appId: '1:720110906425:ios:aec9b3761e466077fff1e8',
    messagingSenderId: '720110906425',
    projectId: 'linerai',
    storageBucket: 'linerai.firebasestorage.app',
    iosBundleId: 'shop.drippingmonks.linerai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPW8cBV1yZd2e6MG-aHKHhflRuHvEKfnI',
    appId: '1:720110906425:web:eff598f33de9cd66fff1e8',
    messagingSenderId: '720110906425',
    projectId: 'linerai',
    authDomain: 'linerai.firebaseapp.com',
    storageBucket: 'linerai.firebasestorage.app',
  );

}